export const initialState = {
  firstName: "",
  lastName: "",
  email: "",
  cnic: "",
  phoneNo: "",
  qualification: "",
  guardianName: "",
  guardianPhoneNo: "",
  address: "",
  gender: "",
  city: "",
  dateOfBirth: "",
  experience: "",
  password: "",
  marital_status: "",
  bio: "",
  designation: "",
  basic_salary: "",
  facilities: "",
  user_image: "",
  cnic_doc: "",
  contract: "",
  resume: "",
};
