export const initialState = {
  firstName: "",
  lastName: "",
  email: "",
  password: "",
  cnic: "",
  phoneNo: "",
  qualification: "",
  guardianName: "",
  guardianPhoneNo: "",
  address: "",
  gender: "",
  city: "",
  dateOfBirth: "",
  marital_status: "",
  bio: "",
  fixed_fee: "",
  fixed_fee_date: "",
  class_id: null,
  user_image: "",
};
