const sampleData = [
  {
    id: 1,
    name: "TechSphere Ltd.",
    ceo: "Ali Khan",
    "company email": "info@techsphere.com",
    "company phone number": "+92 300 1234567",
    "available seats": "25",
    "owner email": "owner@techsphere.com",
    "owner phone number": "+92 322 4455667",
    shifts: "Morning, Evening",
    "time slots": "9:00 AM - 5:00 PM, 6:00 PM - 12:00 AM",
    "fields provided by company": "Software Development, AI, Cloud Computing",
  },
  {
    id: 2,
    name: "CodeCrafters",
    ceo: "Sara Ahmed",
    "company email": "contact@codecrafters.io",
    "company phone number": "+92 301 7654321",
    "available seats": "15",
    "owner email": "owner@codecrafters.io",
    "owner phone number": "+92 333 7788990",
    shifts: "Morning",
    "time slots": "10:00 AM - 6:00 PM",
    "fields provided by company": "Web Development, Mobile Apps, UI/UX Design",
  },
  {
    id: 3,
    name: "NextGen Solutions",
    ceo: "Hassan Raza",
    "company email": "support@nextgensol.com",
    "company phone number": "+92 345 9876543",
    "available seats": "40",
    "owner email": "owner@nextgensol.com",
    "owner phone number": "+92 300 9988776",
    shifts: "Morning, Night",
    "time slots": "8:00 AM - 4:00 PM, 8:00 PM - 4:00 AM",
    "fields provided by company": "Data Science, Cybersecurity, Cloud Hosting",
  },
  {
    id: 4,
    name: "InnoWorks",
    ceo: "Ayesha Noor",
    "company email": "hello@innoworks.net",
    "company phone number": "+92 321 1112233",
    "available seats": "10",
    "owner email": "owner@innoworks.net",
    "owner phone number": "+92 331 2233445",
    shifts: "Evening",
    "time slots": "2:00 PM - 10:00 PM",
    "fields provided by company": "Innovation Labs, AR/VR, Robotics",
  },
  {
    id: 5,
    name: "PixelSoft",
    ceo: "Usman Tariq",
    "company email": "team@pixelsoft.org",
    "company phone number": "+92 333 5557788",
    "available seats": "30",
    "owner email": "owner@pixelsoft.org",
    "owner phone number": "+92 344 6677889",
    shifts: "Morning, Evening",
    "time slots": "9:00 AM - 1:00 PM, 3:00 PM - 9:00 PM",
    "fields provided by company": "Graphic Design, Game Development, Animation",
  },
];

export default sampleData;